# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" # Specify "pip" for Python dependencies
    directory: "/" # Location of package manifests (your requirements.txt is likely in the root)
    schedule:
      interval: "weekly" # Check for updates weekly
    # You can add more options here if needed, e.g.,
    # allow:
    #   - dependency-type: "all" # Update all dependency types (development and production)
    # labels:
    #   - "dependencies"
    # commit-message:
    #   prefix: "deps"
    #   include: "scope"
